- name: Show workspace files (debug)
  run: |
    pwd
    ls -al
    ls -al scripts || true

- name: Ensure data dir exists
  run: mkdir -p data

# ルートにあるなら
- name: Build predict_latest.json
  run: python predict_refresh.py

# scripts/ にあるなら
# - name: Build predict_latest.json
#   run: python scripts/predict_refresh.py
