name: Today Market (09:45 JST)

on:
  schedule:
    - cron: "45 0 * * *"        # JST 09:45 = UTC 00:45
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Show workspace files (debug)
        run: |
          pwd
          ls -al
          echo "----"
          ls -al scripts || true

      - name: Ensure data dir exists
        run: mkdir -p data

      # ★ここが肝心：リポジトリ直下にあるファイルを実行
      #   もし scripts/ 配下に移動したなら下の行を「python scripts/fetch_today_market.py」に戻してください
      - name: Build today_market.json
    　- name: Build today_market.json
      run: |
    mkdir -p data
    python fetch_today_market.py

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/today_market.json
          git commit -m "chore: update today_market.json" || echo "no changes"
          git push
