name: Today Market (09:45 JST)

on:
  schedule:
    - cron: "45 0 * * *"  # JST 09:45
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
      - run: python scripts/fetch_today_market.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/today_market.json
          git commit -m "chore: update today_market.json" || echo "no changes"
          git push
